name: packaging
on: 
  - push

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - name: Install tox
        run: python -m pip install tox
      - name: Run black 
        run: tox -e format


        
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.11"
            toxenv: "py311"
          - version: "3.12"
            toxenv: "py312"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - name: Install tox
        run: python -m pip install tox
      - name: Run test
        run: tox -e ${{ matrix.python.toxenv }}